---
server:
  address: 127.0.0.1
  port: 8080
spring:
  main:
    banner-mode: "OFF"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:h2:./db.h2;AUTO_SERVER_PORT=9090;AUTO_SERVER=TRUE
    username: sa
    password: sa
  mustache:
    enabled: false
    check-template-location: false
logging:
  level:
    root: "warn"
    org.springframework.web: "warn"
    # org.springframework: "warn"
    org.hibernate: "warn"
